### ISSUE TITLE
`hammer dev` returns error

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/tutorial#1]
Happy to help debug given pointing in the right direction. Running the latest Node, npm, and yarn. Seems to be a yarn v. node promise fight, which I'm not too familiar with.

`$hammer dev` returns:
```
yarn run v1.21.1
error Command "hammer-dev-server" not found.
error Command "webpack-dev-server" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[web] cd /Users/price/Repos/hammer-test-blog/web && yarn webpack-dev-server --config ./config/webpack.dev.js exited with code 1
[api] cd /Users/price/Repos/hammer-test-blog/api && yarn hammer-dev-server exited with code 1
(node:2548) UnhandledPromiseRejectionWarning: Error
    at SwitchMapSubscriber.project (/Users/price/.config/yarn/global/node_modules/concurrently/src/completion-listener.js:31:33)
    at SwitchMapSubscriber._next (/Users/price/.config/yarn/global/node_modules/rxjs/internal/operators/switchMap.js:49:27)
    at SwitchMapSubscriber.Subscriber.next (/Users/price/.config/yarn/global/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MapSubscriber._next (/Users/price/.config/yarn/global/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/price/.config/yarn/global/node_modules/rxjs/internal/Subscriber.js:66:18)
    at BufferCountSubscriber._next (/Users/price/.config/yarn/global/node_modules/rxjs/internal/operators/bufferCount.js:52:30)
    at BufferCountSubscriber.Subscriber.next (/Users/price/.config/yarn/global/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/price/.config/yarn/global/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/price/.config/yarn/global/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/price/.config/yarn/global/node_modules/rxjs/internal/Subscriber.js:66:18)
(node:2548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cannikin** [comment]
This is now `yard redwood dev` and should work correctly!
